version: '3.7'

services:
  backend:
    build:
      context: ./backend
    container_name: memories-backend
    hostname: backend
    volumes:
      - ./backend/profile_photos:/backend/profile_photos
      - ./backend/story_images:/backend/story_images
    ports:
      - "8000:8000"
    env_file:
      - ./backend/backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./backend/frontend
    container_name: memories-frontend
    hostname: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/frontend/.env
    depends_on:
      - backend

  db:
    image: "postgis/postgis:15-3.4"
    container_name: memories-db
    hostname: db
    env_file:
      - ./backend/backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
