# Generated by Django 4.1.7 on 2023-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_again',
            field=models.CharField(max_length=128, null=True, verbose_name='password_again'),
        ),
    ]
