# Generated by Django 4.1.7 on 2023-04-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
