# Generated by Django 4.1.7 on 2023-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_date_location_decade_season_specificdate_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decade',
            name='date',
        ),
        migrations.RemoveField(
            model_name='season',
            name='date',
        ),
        migrations.AddField(
            model_name='decade',
            name='date_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='date_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='season_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='specificdate',
            name='date_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specificdate',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
