# Generated by Django 4.1.7 on 2023-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_decade_date_remove_season_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decade',
            name='date_ptr',
        ),
        migrations.RemoveField(
            model_name='season',
            name='date_ptr',
        ),
        migrations.RemoveField(
            model_name='specificdate',
            name='date_ptr',
        ),
        migrations.RemoveField(
            model_name='story',
            name='date_content_type',
        ),
        migrations.RemoveField(
            model_name='story',
            name='date_id',
        ),
        migrations.RemoveField(
            model_name='story',
            name='date_object_id',
        ),
        migrations.AddField(
            model_name='story',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Decade',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='SpecificDate',
        ),
    ]
