# Generated by Django 4.1.7 on 2023-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_story_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date_type',
            field=models.CharField(choices=[('season', 'Season'), ('decade', 'Decade'), ('normal_date', 'Normal Date')], default='normal_date', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='season_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
