# Generated by Django 4.1.7 on 2023-04-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_type',
            field=models.CharField(choices=[('season', 'Season'), ('decade', 'Decade'), ('normal_date', 'Normal Date'), ('interval_date', 'Interval Date')], default='normal_date', max_length=20),
        ),
    ]
