# Generated by Django 4.1.7 on 2023-04-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20230421_0549'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoForStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_for_story', models.ImageField(blank=True, null=True, upload_to='photo_for_Story/')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='stories_photo',
            field=models.ManyToManyField(blank=True, to='user.photoforstory'),
        ),
    ]
