# Generated by Django 4.1.7 on 2023-04-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_story_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_type',
            field=models.CharField(choices=[('year_interval', 'Year Interval'), ('decade', 'Decade'), ('normal_date', 'Normal Date'), ('interval_date', 'Interval Date')], default='normal_date', max_length=20),
        ),
    ]
