# Generated by Django 4.1.7 on 2023-05-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_story_end_year_story_start_year_and_more'),
    ]

    operations = [
    ]
