# Generated by Django 4.1.7 on 2023-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20230508_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.RemoveField(
            model_name='story',
            name='stories_photo',
        ),
        migrations.AlterField(
            model_name='story',
            name='date_type',
            field=models.CharField(choices=[('year_interval', 'Year Interval'), ('year', 'year'), ('normal_date', 'Normal Date'), ('interval_date', 'Interval Date')], default='normal_date', max_length=20),
        ),
        migrations.DeleteModel(
            name='PhotoForStory',
        ),
    ]
