# Generated by Django 4.1.7 on 2023-05-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_story_date_alter_story_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='include_time',
            field=models.BooleanField(default=False),
        ),
    ]
