# Generated by Django 4.2.7 on 2023-11-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(
                choices=[
                    ('new_story', 'New Story Created'),
                    ('story_liked', 'Story Liked'),
                    ('story_unliked', 'Story Unliked'),
                    ('followed_user', 'Followed User'),
                    ('unfollowed_user', 'Unfollowed User'),
                    ('new_commented_on_story', 'Comment on Story'),
                    ('new_comment_on_comment', 'Comment a Story You Commented Before'),
                ],
                max_length=30,
            ),
        ),
    ]
