# Generated by Django 4.2.7 on 2023-11-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_activity_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=255, null=True))
                ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_tags',
        ),
        migrations.AddField(
            model_name='story',
            name='story_tags',
            field=models.ManyToManyField(blank=True, to='user.tag'),
        ),
    ]
