# Generated by Django 4.2.7 on 2023-12-01 17:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_tag_name_storyrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=ckeditor.fields.RichTextField(default='Test Content'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='Test Title', max_length=255),
        ),
    ]
