# Generated by Django 4.2.7 on 2023-12-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_story_content_alter_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyrecommendation',
            name='content_related',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storyrecommendation',
            name='location_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storyrecommendation',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='storyrecommendation',
            name='related_stories',
            field=models.ManyToManyField(related_name='recommendations', to='user.story'),
        ),
        migrations.AddField(
            model_name='storyrecommendation',
            name='tag_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storyrecommendation',
            name='time_related',
            field=models.BooleanField(default=False),
        ),
    ]
