name: Frontend test pipeline
on:
  pull_request:
    paths:
      - 'backend/frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/ci-frontend.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'backend/frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/ci-frontend.yml'
  workflow_dispatch:
jobs:
    frontend-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: "[CI] Frontend test"
          run: |
            echo
            npm install deers > /dev/null 2>&1
            node -e "const deers = require('deers'); console.log(deers()[new Date().getMinutes()]);" || true
            make
            docker --version
            docker-compose --version
            make env-files
            docker compose up -d --build
            docker compose ps
            docker network ls
            docker compose logs frontend
            make git-stats
            docker compose exec -e CI=true -T frontend npm run test -- --coverage --watchAll=false
